### PR TITLE
Patch1

### PR DESCRIPTION
**Pull request by knightwayne**
The link for "complete list of all documented vulnerabilities" was not working. Corrected the path of the link

### CODE REVIEW

**Comment by itaysk** [comment]
@knightwayne I don't see any issue with that link. can you double check?

**Comment by knightwayne** [comment]
Hi @itaysk! In the original file, at the 'click here' position, there was no link. It only showed click here for link. I put up the link in index.md file in my commit, and created a pull request.
Is there anything I have done off track ? (The link is working in my repo.)

**Comment by itaysk** [comment]
Perhaps you are looking at and out of date commit because your PR replaces `({{ site.baseurl }}{% link kbindex.html %})` with `(./kbindex.html)` so the link was there before. Anyway if you go to the actual site at https://aquasecurity.github.io/kube-hunter you can click the link just fine. I'm going to close this, let me know if you think it should be re-opened.

**Comment by knightwayne** [comment]
Hi @itaysk! Sorry got caught up in end-sems. I didn't realised it was done using Jekyll. My mistake, sorry!

**Comment by knightwayne** [comment]
@itaysk, Could you also review my other pull requests [#26](https://github.com/aquasecurity/dcos-universe/pull/26) and [#27](https://github.com/aquasecurity/dcos-universe/pull/27)?
I would delete this comment afterwards.

**Pull request closed without merging**
