### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by SinithH**
## Description
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context. List any dependencies that are required for this change.

## Contribution Guidelines
Please Read through the [Contribution Guidelines](https://github.com/aquasecurity/kube-hunter/blob/master/CONTRIBUTING.md).

## Fixed Issues

Please mention any issues fixed in the PR by referencing it properly in the commit message.
As per the convention, use appropriate keywords such as `fixes`, `closes`, `resolves` to automatically refer the issue.
Please consult [official github documentation](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) for details.

Fixes #(issue)

## "BEFORE" and "AFTER" output

To verify that the change works as desired, please include an output of terminal before and after the changes under headings "BEFORE" and "AFTER".

### BEFORE
Any Terminal Output Before Changes.

### AFTER
Any Terminal Output Before Changes.

## Contribution checklist
 - [x] I have read the Contributing Guidelines.
 - [x] The commits refer to an active issue in the repository.
 - [x] I have added automated testing to cover this case.
 
## Notes
Please mention if you have not checked any of the above boxes.

### CODE REVIEW

**Review by lizrice — APPROVED** [review]
lgtm

**Comment by danielsagi** [comment]
@SinithH 
Please resolve the conflicts and I'll merge asap.

**Comment by SinithH** [comment]
> @SinithH
> Please resolve the conflicts and I'll merge asap.

I have no idea how to

**Comment by danielsagi** [comment]
@SinithH 
No problem at all.
The easiest way is just create a new branch from master, and do the changes manually again. then force push them to this branch. If you get lost you can also just create a new PR, and Ill approve it.

**Comment by SinithH** [comment]
> @SinithH
> No problem at all.
> The easiest way is just create a new branch from master, and do the changes manually again. then force push them to this branch. If you get lost you can also just create a new PR, and Ill approve it.
> Something just got messed in your branch, so git doesn't like it

I opened a new PR. I hope it will be valid for hackotberfest since I actually opened it before 31st of October though there were some conflicts.
new PR - https://github.com/aquasecurity/kube-hunter/pull/403

**Pull request closed without merging**
