### PR TITLE
docs: Vulnerability Types Description

### LINKED ISSUE #253: Document categories
we need to add some documentation of the existing categories and their meaning. 
Also, maybe worth to report the relation to severity until that is changed (https://github.com/aquasecurity/kube-hunter/issues/118)

### PR DESCRIPTION
**Pull request by MiniMarvin**
## Description
Added a description for each vulnerability type that the kube-hunter can find up to now. That's important so each contributor can understand properly which type of vulnerability should use on writing code without the need to look for examples or what that vulnerability type means. 

## Contribution Guidelines
Please Read through the [Contribution Guidelines](https://github.com/aquasecurity/kube-hunter/blob/master/CONTRIBUTING.md).

## Fixed Issues

closes #253 

Fixes #(issue)

## "BEFORE" and "AFTER" output

To verify that the change works as desired, please include an output of terminal before and after the changes under headings "BEFORE" and "AFTER".

### BEFORE
Any Terminal Output Before Changes.

### AFTER
Any Terminal Output Before Changes.

## Contribution checklist
 - [X] I have read the Contributing Guidelines.
 - [X] The commits refer to an active issue in the repository.
 - [ ] I have added automated testing to cover this case.
 
## Notes
As the updates where only in documentation no automation test was written.

### CODE REVIEW

**Comment by iYehuda** [comment]
Hi @MiniMarvin !

I think it is more reasonable to make a reference to more standard definitions of vulnerability and weakness types, see [MITRE CWE](https://cwe.mitre.org/data/definitions/2000.html) for example.
Apart from that, your definitions are about VMs which is more an example than definitions.
I wish to give more general, yet precise definition to newcomers.

**Comment by iYehuda** [comment]
Hi @MiniMarvin !

Any progress with this?
I think adding links to external and standard definitions would be a good idea.
What do you think @lizrice @itaysk ?

**Comment by lizrice** [comment]
Agreed, we should use standard definitions for these rather than making up our own

**Comment by lizrice** [comment]
Closing this PR since we would use a different approach

**Pull request closed without merging**
