### PR TITLE
update gitignore

### PR DESCRIPTION
**Pull request by itaysk**
## Fixed Issues

add `pip-wheel-metadata` to the .gitignore

## Contribution checklist
 - [x] I have read the Contributing Guidelines.
 - [x] The commits refer to an active issue in the repository.
 - [x] I have added automated testing to cover this case.

### CODE REVIEW

**Review by evrardjp — COMMENTED** [review]
How did you get that file? I don't see it after any make/python command in this project.

However, I understand why we have it in .gitignore, if we already have the .egg* present in gitignore. I just have the pip-wheel-metadata in my global gitignore list.

**Comment by itaysk** [comment]
> How did you get that file? 
I just did `make deps` and `make dev-deps`

I saw that this was fixed in pip 20.2.2 which will use a temp dir instead, but I thought it would be better to add it to .getignore anyway

**Comment by evrardjp** [comment]
Yes indeed, I am not against that :) 

I just thought it was worth a message in the commit message to explain the full context.

**Review by danielsagi — APPROVED** [review]
lgtm

**Pull request merged**
