### PR TITLE
Rename root package

### PR DESCRIPTION
**Pull request by iYehuda**
## Description
Rename `src` root package to `kube_hunter`
Depends on #283.
## Fixed Issues
Relates to (but does not resolve) #185 and is a prerequisite to #272 

## Contribution checklist
 - [x] I have read the Contributing Guidelines.
 - [x] The commits refer to an active issue in the repository.
 
## Notes
No tests were added since no new code introduced.

### CODE REVIEW

**Comment by itaysk** [comment]
just making it clear, this PR includes https://github.com/aquasecurity/kube-hunter/pull/283, so can we merge that one and rebase this on master, so the diff will be more relevant?

**Comment by iYehuda** [comment]
> just making it clear, this PR includes #283 right? so can we merge that one first and then rebase this one on master, so the diff will be more relevant?

Correct, I'll mention that in PR description

**Comment by itaysk** [comment]
actually, I'm not sure now looking at https://github.com/aquasecurity/kube-hunter/pull/286/commits and https://github.com/aquasecurity/kube-hunter/pull/283/commits they look identical, what am I missing @iYehuda ?

**Comment by iYehuda** [comment]
> actually, I'm not sure now looking at https://github.com/aquasecurity/kube-hunter/pull/286/commits and https://github.com/aquasecurity/kube-hunter/pull/283/commits they look identical, what am I missing @iYehuda ?

The changes  requested here were mistakenly pushed to #283 as well, so this one made irrelevant

**Comment by iYehuda** [comment]
Closing on behalf of #283

**Pull request closed without merging**
