### PR TITLE
Rename camel var to snake style.

### PR DESCRIPTION
**Pull request by godaji**
Hi, I'm not sure about your style guide, but I thinks you use pep-08, and I found one camel type variable.

Please approve if it helps.

P.S. Thank you for your great open source. :)

### CODE REVIEW

**Comment by itaysk** [comment]
Hi @godaji, thanks for the contribution.

There wasn't any specific guideline so far, but yes snake_case is preferred. 

I run a simple scan of the codebase and found the following places where camelCase is used. It would be better if we fixed all similar cases in the same PR, if you don't mind adding that?

```
$ grep -P --include '*.py' -r ' [a-z]+[A-Z]+[a-zA-Z]*[ ]?=' .
./src/core/types.py:    publishedVulnerabilities = 0
./src/modules/discovery/kubectl.py:            versionInfo = subprocess.check_output("kubectl version --client", stderr=subprocess.STDOUT)
./src/modules/discovery/kubectl.py:                versionInfo = versionInfo.decode()
./src/modules/hunting/aks.py:            podNamespace=container["namespace"],
./src/modules/hunting/aks.py:            podID=container["pod"],
./src/modules/hunting/aks.py:            containerName=container["name"]
./src/modules/hunting/kubelet.py:                podNamespace=self.pod["namespace"],
./src/modules/hunting/kubelet.py:                podID=self.pod["name"],
./src/modules/hunting/kubelet.py:                containerName=self.pod["container"]
./src/modules/hunting/kubelet.py:                podNamespace=self.pod["namespace"],
./src/modules/hunting/kubelet.py:                podID=self.pod["name"],
./src/modules/hunting/kubelet.py:                containerName=self.pod["container"],
./src/modules/hunting/kubelet.py:                podNamespace=self.pod["namespace"],
./src/modules/hunting/kubelet.py:                podID=self.pod["name"],
./src/modules/hunting/kubelet.py:                podNamespace='test',
./src/modules/hunting/kubelet.py:                podID='test',
./src/modules/hunting/kubelet.py:                containerName='test',
./src/modules/hunting/kubelet.py:                podNamespace=self.pod["namespace"],
./src/modules/hunting/kubelet.py:                podID=self.pod["name"],
./src/modules/hunting/kubelet.py:                containerName=self.pod["container"],
./src/modules/hunting/kubelet.py:            podNamespace=container["namespace"],
./src/modules/hunting/kubelet.py:            podID=container["pod"],
./src/modules/hunting/kubelet.py:            containerName=container["name"],
./src/modules/hunting/kubelet.py:                        podNamespace=pod_data["metadata"]["namespace"],
./src/modules/hunting/kubelet.py:                        podID=pod_data["metadata"]["name"],
./src/modules/hunting/kubelet.py:                        containerName=container_data["name"]
./src/modules/hunting/mounts.py:            podNamespace=container["namespace"],
./src/modules/hunting/mounts.py:            podID=container["pod"],
./src/modules/hunting/mounts.py:            containerName=container["name"],
./src/modules/report/dispatchers.py:        dispatchMethod = os.environ.get(
./src/modules/report/dispatchers.py:        dispatchURL = os.environ.get(
```

**Comment by godaji** [comment]
Hi, I changed all camelCase as snake_case.
Please review code :)

**Comment by itaysk** [comment]
thank you @godaji

**Comment by godaji** [comment]
Thank you :)

**Pull request merged**
