### PR TITLE
full text search

### PR DESCRIPTION
**Pull request by RobbiNespu**
## Description
Allow to searching full text on all KB pages  as issue #240 

## Contribution Guidelines
Please Read through the [Contribution Guidelines](https://github.com/aquasecurity/kube-hunter/blob/master/CONTRIBUTING.md).

## Contribution checklist
 - [ /] I have read the Contributing Guidelines.
 - [ /] The commits refer to an active issue in the repository.
 - [ X] I have added automated testing to cover this case.
 
## Notes
Please mention if you have not checked any of the above boxes.

### CODE REVIEW

**Comment by itaysk** [comment]
Thanks for the PR! can you please incorporate the results into the existing search box? if it can replace the existing functionality that's fine too.

**Comment by RobbiNespu** [comment]
It much better to replace since it also can search the ID. The best design is to put on the top of content because result are show in list. since sidebar design is fixed. It will be ugly a bit.

**Comment by RobbiNespu** [comment]
image

**Comment by RobbiNespu** [comment]
Hi @itaysk , I commit some changes as mentioned. Could you check if satisfying the expectation?

**Comment by itaysk** [comment]
Thanks @RobbiNespu for your efforts. First, I cannot run this locally, getting some client side errors. But regardless, I now see that this is not in fact a full-text search, because it only search the metadata of articles. It's definitely an improvement over the current lookup by only vid, but I think if merged, this PR will quickly be superseded by another PR that adds full-text search so I don't see value in investing in this one now.
(This is a good lesson to follow the contribution guidelines and first discuss the feature in an Issue before submitting a PR)
I think a better solution would be to leverage an external search service for indexing, so I'm deferring the discussion to the associated issue. Please feel free to discuss the solution over there. Once we agree on a solution you can submit a new PR.

**Comment by lizrice** [comment]
Closing based on @itaysk comment

**Pull request closed without merging**
