### PR TITLE
adding codecoverage

### PR DESCRIPTION
**Pull request by butuzov**
Added codecov support in regards of aquasecurity/kube-hunter#174

1) Register at https://codecov.io
2) Add/Sync repository
3) Add CODECOV_TOKEN to travis-ci.org via settings.
4) Run and enjoy it.

I would also recommend to add https://codecov.io/ bot so it can report on code coverage changes.

here is how it was look like for my local branch 

image

and here is how it look like on codecov page https://codecov.io/gh/butuzov/kube-hunter

### CODE REVIEW

**Comment by butuzov** [comment]
@codecov-io didn't know you are already enabled here =)

**Comment by butuzov** [comment]
Conflicts are resolved.

**Comment by butuzov** [comment]
Guess you all overwhelmed with hacktoberfest?

**Comment by lizrice** [comment]
Hm, for some reason GitHub is showing me that the statuses aren't all passed though they clearly are. Meanwhile, I just noticed this has a setup.cfg file, so @iYehuda does that affect anything you're doing?

**Comment by butuzov** [comment]
All I see is a message 
> "The base branch restricts merging to authorized users. "

As for `setup.cfg` its just one of the ways to provide configuration for `pytest` and other py tooling supported by different packages. `coverage` and `pytest` both support it, so it's a way to go many python developers.

**Comment by lizrice** [comment]
Fixes #174

**Comment by butuzov** [comment]
p.s.
hacktoberfest is over. any chance I can get your book signed?

**Pull request merged**
